In [423]:
def unknown_classification(a, b, z):
    if a+b+z < 1:
        return 0
    else:
        return 1

In [424]:
import random
random_data = [(x, y, z, unknown_classification(x, y, z), abs(1-unknown_classification(x, y, z))) 
                                           for x in [random.random()/2 for x in range(10)]
                                           for y in [random.random()/2 for x in range(10)]
                                           for z in [random.random()/2 for x in range(10)]]

In [425]:
random_data[:10]

[(0.4411822656325668, 0.1559806374192696, 0.17304512820595774, 0, 1),
 (0.4411822656325668, 0.1559806374192696, 0.19626311295203386, 0, 1),
 (0.4411822656325668, 0.1559806374192696, 0.4691841008076463, 1, 0),
 (0.4411822656325668, 0.1559806374192696, 0.2510769851363644, 0, 1),
 (0.4411822656325668, 0.1559806374192696, 0.4164982751557643, 1, 0),
 (0.4411822656325668, 0.1559806374192696, 0.08497428815101626, 0, 1),
 (0.4411822656325668, 0.1559806374192696, 0.18083463517849835, 0, 1),
 (0.4411822656325668, 0.1559806374192696, 0.38540733578299463, 0, 1),
 (0.4411822656325668, 0.1559806374192696, 0.3941817765564385, 0, 1),
 (0.4411822656325668, 0.1559806374192696, 0.1558932304775713, 0, 1)]

In [469]:
import numpy as np 
data = np.array(random_data)
np.random.shuffle(data)

In [470]:
data.shape

(1000, 5)

In [471]:
train_data = data[:int(data.shape[0]*.7)]

In [472]:
len(train_data)

700

In [473]:
test_data = data[train_data.shape[0]:]

In [474]:
len(test_data)

300

In [475]:
x_train = train_data[:, :3]
x_test = test_data[:, :3]

In [476]:
x_train

array([[ 0.04385478,  0.45538533,  0.16354778],
       [ 0.48563993,  0.02898427,  0.48524876],
       [ 0.04385478,  0.04918372,  0.48144992],
       ..., 
       [ 0.13775181,  0.14198826,  0.45988384],
       [ 0.38435692,  0.2557829 ,  0.15324224],
       [ 0.04385478,  0.29377507,  0.3304793 ]])

In [477]:
y_train = train_data[:, 3:]
y_test = test_data[:, 3: ]

In [478]:
y_train

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       ..., 
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]])

In [479]:
import keras

In [480]:
from keras.models import Sequential
from keras.layers import Dense, Flatten

model = Sequential()
model.add(Dense(3, input_shape=x_train.shape[1:]))
model.add(Dense(2, activation='softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_64 (Dense)             (None, 3)                 12        
_________________________________________________________________
dense_65 (Dense)             (None, 2)                 8         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [481]:
# compile the model
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', 
                  metrics=['accuracy'])

In [482]:
model.fit(x_train, y_train, epochs=20, verbose=1)

Epoch 1/20
700/700 [==============================] - 1s 2ms/step - loss: 0.6773 - acc: 0.6986
Epoch 2/20
700/700 [==============================] - 0s 195us/step - loss: 0.6472 - acc: 0.8686
Epoch 3/20
700/700 [==============================] - 0s 194us/step - loss: 0.6208 - acc: 0.8771
Epoch 4/20
700/700 [==============================] - 0s 201us/step - loss: 0.5957 - acc: 0.8771
Epoch 5/20
700/700 [==============================] - 0s 215us/step - loss: 0.5710 - acc: 0.8771
Epoch 6/20
700/700 [==============================] - 0s 212us/step - loss: 0.5465 - acc: 0.8771
Epoch 7/20
700/700 [==============================] - 0s 195us/step - loss: 0.5235 - acc: 0.8771
Epoch 8/20
700/700 [==============================] - 0s 203us/step - loss: 0.5020 - acc: 0.8771
Epoch 9/20
700/700 [==============================] - 0s 210us/step - loss: 0.4820 - acc: 0.8771
Epoch 10/20
700/700 [==============================] - 0s 216us/step - loss: 0.4640 - acc: 0.8771
Epoch 11/20
700/700 [==========

In [455]:
score = model.evaluate(x_test, y_test)

300/300 [==============================] - 0s 1ms/step


In [456]:
print('Test accurracy: %.2f' % score[1])

Test accurracy: 0.87


In [462]:
model.predict(x_test[:10])

array([[ 0.1248996 ,  0.87510037],
       [ 0.1255036 ,  0.87449634],
       [ 0.12356329,  0.87643671],
       [ 0.12564658,  0.87435341],
       [ 0.12549916,  0.87450081],
       [ 0.12485445,  0.87514555],
       [ 0.12471019,  0.87528986],
       [ 0.12543291,  0.87456709],
       [ 0.12531188,  0.87468809],
       [ 0.12329019,  0.87670988]], dtype=float32)